name       : google-cloud-sdk
version    : 348.0.0
release    : 18
source     :
    - https://dl.google.com/dl/cloudsdk/release/downloads/for_packagers/linux/google-cloud-sdk_348.0.0.orig.tar.gz : 03f0d4a3ceba5db7c46d0b9564b4f471d611d80e8dcf18f837164c08f41f9c78
extract    : no
strip      : no
license    : Apache-2.0
homepage   : https://cloud.google.com/sdk
component  : network.clients
summary    : Command-line tools for the Google Cloud Platform.
description: |
    A set of command-line tools for the Google Cloud Platform. Includes gcloud (with beta and alpha commands), gsutil, and bq.
environment: |
    export CLOUDSDK_INSTALL_DIR=$installdir/usr/share/google-cloud-sdk
install    : |
    mkdir -p $CLOUDSDK_INSTALL_DIR
    tar -xzvf $sources/google-cloud-sdk_%version%.orig.tar.gz -C $installdir/usr/share

    python3 $CLOUDSDK_INSTALL_DIR/bin/bootstrapping/install.py \
    --quiet \
    --usage-reporting False \
    --path-update False \
    --bash-completion False \
    --additional-components "" \
    1 > /dev/null

    # do a cleanup
    find $installdir -name '__pycache__' -type d -exec rm -rf {} +
    rm -rf $CLOUDSDK_INSTALL_DIR/.install
    rm -rf $CLOUDSDK_INSTALL_DIR/install.*

    # install manpages
    mv -f $CLOUDSDK_INSTALL_DIR/help/man $installdir/usr/share/
    chmod 00644 $installdir/usr/share/man
    chmod 00644 $installdir/usr/share/man/man1
    rm -rf $CLOUDSDK_INSTALL_DIR/help

    # fix execute rights
    find $CLOUDSDK_INSTALL_DIR -name "*.html" -o -name "*.json" -exec chmod -x {} \;
    find $CLOUDSDK_INSTALL_DIR -name "*_test.py" -exec chmod +x {} \;

    # Install profile.d script sets up needed environment variables
    install -D -m 00644 $pkgfiles/50-google-cloud-sdk.sh $installdir/usr/share/defaults/etc/profile.d/50-google-cloud-sdk.sh
